const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { createApp } = require('../server');

test('fluxo completo: sessão, vínculos, foto, edição, assinatura, versões e persistência', async (t) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'diario-api-test-'));
  let app = createApp({ directory });
  await new Promise((resolve) => app.server.listen(0, '127.0.0.1', resolve));
  let base = `http://127.0.0.1:${app.server.address().port}/api`;
  t.after(async () => { await new Promise((resolve) => app.server.close(resolve)); fs.rmSync(directory, { recursive: true, force: true }); });
  async function api(route, token, method = 'GET', body) {
    const response = await fetch(base + route, { method, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: body ? JSON.stringify(body) : undefined });
    return { status: response.status, data: await response.json() };
  }
  async function login(email) {
    const result = await api('/login', null, 'POST', { email, password: '123456' });
    assert.equal(result.status, 200); assert.equal(result.data.user.passwordHash, undefined); return result.data.token;
  }
  assert.equal((await api('/state')).status, 401);
  const owner = await login('dono@diariodeobra.com.br');
  const operator = await login('responsavel@diariodeobra.com.br');
  const client = await login('cliente@diariodeobra.com.br');
  assert.equal((await api('/state', owner)).data.works.length, 2);
  const state = (await api('/state', client)).data;
  assert.equal(state.works.length, 1); assert.equal(state.users.length, 0);
  assert.equal((await api('/works/obra-atelie', client, 'PATCH', {})).status, 403);
  assert.equal((await api('/reports', client, 'POST', {})).status, 403);
  assert.equal((await api('/photos', client, 'POST', {})).status, 403);
  assert.equal((await api('/works', operator, 'POST', {})).status, 403);
  assert.equal((await api('/operators', client, 'POST', {})).status, 403);
  const newOperator = await api('/operators', owner, 'POST', { name: 'Outro responsável', email: 'novo@responsavel.com', password: '123456' });
  assert.equal(newOperator.status, 201);
  const operatorTwo = await login('novo@responsavel.com');
  assert.equal((await api('/state', operatorTwo)).data.works.length, 0);
  assert.equal((await api('/works', owner, 'POST', { name: 'Obra teste', address: 'Endereço fictício', contract: 'T-001', startDate: '2026-01-01', clientIds: ['client'], operatorIds: ['client'] })).status, 400);
  const newWork = await api('/works', owner, 'POST', { name: 'Obra teste', address: 'Endereço fictício', contract: 'T-001', startDate: '2026-01-01', clientIds: ['client'], operatorIds: [newOperator.data.user.id] });
  assert.equal(newWork.status, 201);
  assert.equal((await api('/state', operatorTwo)).data.works.length, 1);
  const badBody = await fetch(base + '/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: 'null' });
  assert.equal(badBody.status, 400);
  assert.equal((await api('/login', null, 'POST', { email: 'dono@diariodeobra.com.br', password: 'errada' })).status, 401);
  const body = { name: 'Novo Cliente', email: 'novo@cliente.com', password: '123456', passwordConfirmation: '123456', consent: true, role: 'owner' };
  const registered = await api('/register', null, 'POST', body);
  assert.equal(registered.status, 201); assert.equal(registered.data.user.role, 'client');
  assert.equal((await api('/register', null, 'POST', body)).status, 409);
  assert.equal((await api('/register', null, 'POST', { ...body, email: 'invalid@client.com', consent: false })).status, 400);
  const fresh = await login(body.email);
  assert.equal((await api('/state', fresh)).data.works.length, 0);
  await api('/works/obra-jardins', owner, 'PATCH', { clientIds: ['client', registered.data.user.id] });
  assert.equal((await api('/state', fresh)).data.works.length, 1);
  const png = 'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=';
  const upload = await api('/photos', operator, 'POST', { workId: 'obra-jardins', consent: true, base64: png });
  assert.equal(upload.status, 201);
  assert.equal((await api(`/photos/${upload.data.photo.id}`, client)).status, 200);
  const otherPhoto = await api('/photos', operator, 'POST', { workId: 'obra-atelie', consent: true, base64: png });
  assert.equal((await api(`/photos/${otherPhoto.data.photo.id}`, client)).status, 404);
  const fields = { workId: 'obra-jardins', date: '2026-01-01', activities: 'Execução do serviço com foto.', progress: 40, photos: [upload.data.photo.id] };
  assert.equal((await api('/reports', operator, 'POST', { ...fields, date: '2026-02-30' })).status, 400);
  assert.equal((await api('/reports', operator, 'POST', { ...fields, progress: null })).status, 400);
  assert.equal((await api('/reports', operatorTwo, 'POST', fields)).status, 404);
  assert.equal((await api('/reports', operator, 'POST', { ...fields, photos: [otherPhoto.data.photo.id] })).status, 400);
  const created = await api('/reports', operator, 'POST', fields);
  assert.equal(created.status, 201);
  const id = created.data.report.id;
  assert.equal((await api('/reports', operator, 'POST', fields)).status, 409);
  assert.equal((await api(`/reports/${id}`, operator, 'PATCH', { ...fields, version: 1 })).status, 403);
  assert.equal((await api(`/reports/${id}`, owner, 'PATCH', { ...fields, version: 0 })).status, 409);
  const edited = await api(`/reports/${id}`, owner, 'PATCH', { ...fields, activities: 'Atividade revisada pelo dono.', version: 1 });
  assert.equal(edited.status, 200); assert.equal(edited.data.report.versions.length, 2);
  assert.equal(edited.data.report.versions[0].content.activities, fields.activities);
  assert.equal((await api(`/reports/${id}/sign`, client, 'POST', { confirm: true, version: 2 })).status, 403);
  assert.equal((await api(`/reports/${id}/sign`, owner, 'POST', { confirm: true, version: 1 })).status, 409);
  const signed = await api(`/reports/${id}/sign`, owner, 'POST', { confirm: true, version: 2 });
  assert.equal(signed.status, 200); assert.equal(signed.data.report.signature.authorId, 'owner');
  assert.equal(signed.data.report.versions.length, 3);
  assert.equal((await api(`/reports/${id}`, owner, 'PATCH', { ...fields, version: 3 })).status, 409);
  assert.equal((await api(`/reports/${id}/sign`, owner, 'POST', { confirm: true, version: 3 })).status, 409);
  const clientRead = await api(`/reports/${id}`, fresh);
  assert.equal(clientRead.data.report.status, 'signed');
  await new Promise((resolve) => app.server.close(resolve));
  app = createApp({ directory });
  await new Promise((resolve) => app.server.listen(0, '127.0.0.1', resolve));
  base = `http://127.0.0.1:${app.server.address().port}/api`;
  assert.equal((await api(`/reports/${id}`, fresh)).data.report.signature.contentHash, signed.data.report.signature.contentHash);
  const persisted = JSON.parse(fs.readFileSync(path.join(directory, 'data.json'), 'utf8'));
  assert.equal(persisted.reports.find((r) => r.id === id).versions[1].previousHash, persisted.reports.find((r) => r.id === id).versions[0].hash);
  assert.equal(persisted.users.some((u) => u.password || !u.passwordHash), false);
  assert.equal(persisted.sessions.some((s) => s.token), false);
  await api('/logout', fresh, 'POST'); assert.equal((await api('/state', fresh)).status, 401);
});
