import { StyleSheet } from 'react-native';
import { colors } from '../../theme/tokens';
export default StyleSheet.create({
  screen: { flex: 1, backgroundColor: colors.canvas },
  topbar: { paddingHorizontal: 20, minHeight: 80, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', backgroundColor: colors.surface, borderBottomWidth: 1, borderColor: '#DDE4EF' },
  brandLine: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1 },
  mark: { width: 36, height: 40, backgroundColor: colors.brand, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  markText: { color: colors.white, fontSize: 24, fontWeight: '800' },
  brand: { color: colors.ink, fontSize: 18, fontWeight: '800' },
  role: { color: colors.muted, fontSize: 13, marginTop: 3 },
  logout: { minWidth: 50, minHeight: 44, justifyContent: 'center', alignItems: 'center' },
  logoutText: { color: colors.actionPressed, fontSize: 14, fontWeight: '700' },
  scroll: { flex: 1 },
  content: { padding: 20, paddingBottom: 32 },
  caption: { color: colors.muted, fontSize: 14, lineHeight: 20, marginBottom: 10 },
  title: { color: colors.ink, fontSize: 28, fontWeight: '800', lineHeight: 35, marginBottom: 10, letterSpacing: -0.4 },
  subtitle: { color: colors.muted, fontSize: 16, lineHeight: 24, marginBottom: 24 },
  section: { color: colors.ink, fontSize: 20, lineHeight: 26, fontWeight: '700', marginTop: 10, marginBottom: 12 },
  body: { color: colors.ink, fontSize: 16, lineHeight: 25, marginBottom: 20 },
  small: { color: colors.muted, fontSize: 13, lineHeight: 20 },
  summary: { borderRadius: 12, paddingVertical: 20, paddingHorizontal: 16, backgroundColor: colors.brand, flexDirection: 'row', marginBottom: 24 },
  summaryItem: { flex: 1, gap: 5 },
  summaryValue: { color: colors.white, fontSize: 30, fontWeight: '800' },
  summaryLabel: { color: colors.textOnBrand, fontSize: 13 },
  summaryDivider: { width: 1, backgroundColor: '#446AA9', marginRight: 20 },
  primaryAction: { marginBottom: 14 },
  listHeading: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 8 },
  workRow: { backgroundColor: colors.surface, borderWidth: 1, borderColor: '#DDE4EF', borderRadius: 12, padding: 16, marginBottom: 14 },
  workTop: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'center', gap: 8, marginBottom: 14 },
  contract: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  workStatus: { color: '#0F654B', backgroundColor: '#EAF6F0', paddingVertical: 4, paddingHorizontal: 7, borderRadius: 5, fontSize: 12, fontWeight: '600' },
  workName: { color: colors.ink, fontSize: 20, fontWeight: '700', marginBottom: 7 },
  workBottom: { borderTopWidth: 1, borderColor: '#E4EAF2', marginTop: 14, paddingTop: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  rowTitle: { color: colors.ink, fontSize: 16, lineHeight: 22, fontWeight: '700', marginBottom: 4 },
  rowDescription: { color: colors.muted, fontSize: 14, lineHeight: 21 },
  chevron: { fontSize: 24, color: colors.actionPressed },
  pressed: { opacity: 0.7 },
  live: { fontSize: 13, color: colors.muted, textAlign: 'center', marginTop: 14 },
  empty: { backgroundColor: colors.focusWash, borderRadius: 12, padding: 18, marginTop: 10 },
  navigation: { flexDirection: 'row', minHeight: 68, backgroundColor: colors.surface, borderTopWidth: 1, borderColor: '#DDE4EF' },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navIcon: { color: colors.muted, fontSize: 22 },
  navLabel: { color: colors.muted, fontSize: 12, fontWeight: '600' },
  navActive: { color: colors.actionPressed },
  errorBox: { padding: 12, gap: 10, borderRadius: 10, backgroundColor: colors.errorWash, marginBottom: 16 },
  error: { color: colors.error, fontSize: 15, lineHeight: 22 },
  guideItem: { flexDirection: 'row', gap: 14, paddingVertical: 16, borderBottomWidth: 1, borderColor: colors.border },
  guideNumber: { color: colors.actionPressed, fontSize: 22, fontWeight: '800' },
  guideText: { color: colors.ink, fontSize: 17, lineHeight: 26, flex: 1 },
  question: { color: colors.ink, fontWeight: '700', fontSize: 16, marginBottom: 8 },
  account: { borderBottomWidth: 1, borderColor: colors.border, paddingBottom: 20, marginBottom: 20 },
  back: { minHeight: 44, justifyContent: 'center', marginBottom: 8 },
  link: { color: colors.actionPressed, fontWeight: '700', fontSize: 15 },
  filter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  filterButton: { minHeight: 44, padding: 8 },
  reportRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 18, borderBottomWidth: 1, borderColor: colors.border },
  dateBlock: { width: 56, backgroundColor: colors.focusWash, paddingVertical: 10, alignItems: 'center', borderRadius: 10 },
  dateDay: { fontSize: 24, fontWeight: '800', color: colors.brand },
  dateMonth: { fontSize: 10, color: colors.muted },
  reportCopy: { flex: 1 },
  skeleton: { height: 90, borderRadius: 12, backgroundColor: '#E3EAF3', marginVertical: 10 },
});
